### ISSUE TITLE
there is a very hard Maze env

### ISSUE THREAD

**Issue by zdx3578** [NeuromorphicComputing/STPN#2]
https://github.com/jurgisp/memory-maze

Memory Maze
Memory Maze is a 3D domain of randomized mazes designed for evaluating the long-term memory abilities of RL agents. Memory Maze isolates long-term memory from confounding challenges, such as exploration, and requires remembering several pieces of information: the positions of objects, the wall layout, and keeping track of agent’s own position.

**Comment by hector-gr** [comment]
Hello, 

Thank you for your interest in our work, and for the suggestion of a different task.

Indeed such tasks would be interesting to test the long-term memory abilities of STPN, and to understand its behaviour better. 

Although improved long-term memorisation is not among STPN's claimed abilities, STPN could also show some benefits in the environment you cite. Since solving such a memory maze can be thought of a task composed of 'sub-tasks', the adaptation within episode provided by short-term plasticity would likely help adjusting to and switching between sub-tasks.

**Comment by zdx3578** [comment]
@hector-gr any advice in integrate memory-maze env ?
